apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
  namespace: playwright-tests
  labels:
    app: demo-app
    app.kubernetes.io/part-of: playwright-poc
spec:
  type: ClusterIP
  selector:
    app: demo-app
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
